version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      all-github-actions:
        patterns:
          - '*'

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      all-python-dependencies:
        patterns:
          - '*'
